import { useState, useEffect, useRef } from "react";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Bot, CheckCircle2, HeartPulse, Loader2, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { useI18n } from "@/i18n";
import { askTalkToCareCase, confirmCareAssistantAction, proposeCareAssistantAction } from "@/lib/social.functions";

const ACTIONS=["create_task","add_to_care_plan","request_document","start_risk_reassessment","find_resource","create_referral","schedule_follow_up","supervisor_review","request_legal_review","draft_case_summary","prepare_closure_checklist"];
const label=(v:string,es:boolean)=>{const x:Record<string,[string,string]>={critical:["Críticos","Critical"],action_required:["Requiere acción","Action required"],incomplete:["Incompletos","Incomplete"],monitor:["En monitoreo","Monitor"],complete:["Completos","Complete"],create_task:["Crear tarea","Create task"],add_to_care_plan:["Agregar al plan","Add to care plan"],request_document:["Solicitar documento","Request document"],start_risk_reassessment:["Iniciar reevaluación","Start risk reassessment"],find_resource:["Buscar recurso","Find resource"],create_referral:["Crear canalización","Create referral"],schedule_follow_up:["Programar seguimiento","Schedule follow-up"],supervisor_review:["Enviar a supervisión","Send for supervisor review"],request_legal_review:["Solicitar revisión jurídica","Request legal review"],draft_case_summary:["Borrador de resumen","Draft case summary"],prepare_closure_checklist:["Preparar lista de cierre","Prepare closure checklist"]};return x[v]?(es?x[v][0]:x[v][1]):v.replaceAll("_"," ")};

export function TalkToCareCase({caseId}:{caseId:string}){
 const {locale}=useI18n();const es=locale==="es";const askFn=useServerFn(askTalkToCareCase);const proposeFn=useServerFn(proposeCareAssistantAction);const confirmFn=useServerFn(confirmCareAssistantAction);
 const [question,setQuestion]=useState("");const [result,setResult]=useState<any>(null);const [proposal,setProposal]=useState<any>(null);
 const lastCheckRef=useRef<boolean|null>(null);
 const ask=useMutation({mutationFn:(healthCheck:boolean)=>{lastCheckRef.current=healthCheck;return askFn({data:{caseId,question:healthCheck?(es?"Ejecutar revisión integral del caso":"Run complete case health check"):question,language:es?"es":"en",healthCheck}})},onSuccess:setResult,onError:(e:any)=>toast.error(e.message)});
 const propose=useMutation({mutationFn:(actionType:string)=>proposeFn({data:{caseId,runId:result?.runId,actionType:actionType as any,title:label(actionType,es),details:{source:"talk_to_care_case"}}}),onSuccess:setProposal,onError:(e:any)=>toast.error(e.message)});
 const confirm=useMutation({mutationFn:()=>confirmFn({data:{proposalId:proposal.id,confirm:true}}),onSuccess:x=>{setProposal(x);toast.success(es?"Acción confirmada y registrada":"Action confirmed and recorded")},onError:(e:any)=>toast.error(e.message)});
 
 const prevLocaleRef=useRef(locale);
 useEffect(()=>{
   if(prevLocaleRef.current!==locale){
     prevLocaleRef.current=locale;
     if(result&&lastCheckRef.current!==null){
       ask.mutate(lastCheckRef.current);
     }
   }
 },[locale,result]);
 const r=result?.response,h=r?.health_check;
 return <section className="space-y-4"><div className="rounded-xl border border-primary/30 bg-primary/5 p-5"><h3 className="flex items-center gap-2 text-lg font-semibold"><Bot className="h-5 w-5 text-primary"/>{es?"Consultar Caso de Atención":"Talk to Care Case"}</h3><p className="text-sm text-muted-foreground">{es?"Analiza únicamente información autorizada del caso seleccionado. No cambia riesgos, consentimiento, planes, referencias ni estado del caso.":"Analyzes only authorized information from the selected case. It does not change risk, consent, plans, referrals, or case status."}</p><textarea rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={es?"¿Qué falta en este caso? ¿Qué requiere seguimiento?":"What is missing? What needs follow-up?"} className="mt-3 w-full rounded-lg border border-border bg-background p-3 text-sm"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={question.trim().length<2||ask.isPending} onClick={()=>ask.mutate(false)} className="rounded bg-primary px-4 py-2 text-sm text-primary-foreground">{ask.isPending&&<Loader2 className="mr-2 inline h-4 w-4 animate-spin"/>}{es?"Consultar":"Ask"}</button><button disabled={ask.isPending} onClick={()=>ask.mutate(true)} className="rounded border border-primary px-4 py-2 text-sm text-primary"><HeartPulse className="mr-2 inline h-4 w-4"/>{es?"Ejecutar revisión de salud del caso":"Run Case Health Check"}</button></div></div>
 {r&&<><div className="grid gap-3 lg:grid-cols-2"><Panel title={es?"Estado actual del caso":"Current case status"}><p>{r.current_case_status.summary}</p><p className="text-xs text-muted-foreground">{r.current_case_status.last_activity??"—"}</p></Panel><Panel title={es?"Faltante o incompleto":"Missing or incomplete"}>{r.missing_or_incomplete.length?r.missing_or_incomplete.map((x:any)=><Item key={x.code} x={x}/>):<p>{es?"Nada identificado por las reglas actuales.":"Nothing identified by current rules."}</p>}</Panel><Panel title={es?"Riesgos que requieren revisión":"Risks requiring review"}>{r.risks_requiring_review.length?r.risks_requiring_review.map((x:any)=><Item key={x.code} x={x}/>):<p>{es?"No se detectaron alertas críticas deterministas.":"No deterministic critical alerts found."}</p>}</Panel><Panel title={es?"Próximos pasos recomendados":"Recommended next steps"}>{r.recommended_next_steps.map((x:any,i:number)=><div key={i} className="rounded border border-border p-2 text-sm"><b>{x.action}</b><p>{x.responsible_role} · {x.suggested_due_date} · {x.consent_required?(es?"Requiere revisar consentimiento":"Consent review required"):(es?"Sin requisito identificado":"No requirement identified")}</p><p className="text-xs text-muted-foreground">{x.supporting_record}</p></div>)}</Panel></div>
 {h&&<div className="grid gap-3 md:grid-cols-5">{[["critical",h.critical],["action_required",h.action_required],["incomplete",h.incomplete],["monitor",h.monitor],["complete",h.complete]].map(([name,rows]:any)=><Panel key={name} title={label(name,es)}><b className="text-2xl">{rows.length}</b>{rows.slice(0,3).map((x:any)=><Item key={x.code} x={x}/>)}</Panel>)}</div>}
 {r.answer&&<Panel title={es?"Respuesta":"Answer"}><p className="whitespace-pre-wrap text-sm leading-relaxed">{r.answer}</p><p className="text-xs text-muted-foreground">{r.answer_source==="ai"?(es?"Generado con los proveedores de IA configurados, sobre hechos del expediente.":"Generated with the configured AI providers, grounded on case records."):(es?"Resultado determinista de las reglas de atención integral.":"Deterministic Comprehensive Care rule output.")}{r.answer_error?` · ${r.answer_error}`:""}</p></Panel>}
 {!!r.knowledge_suggestions?.length&&<Panel title={es?"Guía del Centro de Conocimiento (no es un hecho del caso)":"Knowledge Center guidance (not a case fact)"}>{r.knowledge_suggestions.map((k:any)=><div key={k.id} className="rounded border border-border p-2 text-sm"><b>{k.title}</b><p className="text-xs text-muted-foreground">KNOWLEDGE GUIDANCE · {k.category??"—"} · v{k.version}</p></div>)}</Panel>}
 <Panel title={es?"Fuentes del caso":"Sources"}>{r.sources.map((x:string)=><p key={x} className="text-xs">{x}</p>)}</Panel>
 {!!r.resource_recommendations?.length&&<Panel title={es?"Recursos autorizados para revisión":"Resources for review"}>{r.resource_recommendations.map((x:any)=><div key={x.id} className="rounded border border-border p-2 text-sm"><b>{x.official_name}</b><p>{(x.services??[]).join(", ")} · {[x.municipality,x.state_code].filter(Boolean).join(", ")} · {x.cost_type}</p>{x.warning&&<p className="text-warning">{x.warning}</p>}</div>)}</Panel>}
 <div className="rounded border border-warning/30 bg-warning/10 p-3 text-xs"><ShieldAlert className="mr-2 inline h-4 w-4"/>{r.professional_review_notice}</div>
 <Panel title={es?"Proponer acción — requiere confirmación":"Propose action — confirmation required"}><div className="flex flex-wrap gap-2">{ACTIONS.map(x=><button key={x} onClick={()=>propose.mutate(x)} className="rounded border border-border px-3 py-2 text-xs">{label(x,es)}</button>)}</div>{proposal&&<div className="rounded-lg border border-primary/30 p-3"><p className="font-semibold">{proposal.preview?.title}</p><p className="text-xs text-muted-foreground">{proposal.preview?.warning}</p>{proposal.status==="proposed"?<button disabled={confirm.isPending} onClick={()=>confirm.mutate()} className="mt-2 rounded bg-primary px-3 py-2 text-xs text-primary-foreground">{es?"Confirmar acción":"Confirm action"}</button>:<p className="mt-2 text-sm text-success"><CheckCircle2 className="mr-1 inline h-4 w-4"/>{es?"Confirmada":"Confirmed"}</p>}</div>}</Panel></>}
 </section>
}
function Item({x}:{x:any}){return <div className="rounded border border-border p-2 text-xs"><b>{x.message}</b><p className="text-muted-foreground">{x.source}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="space-y-2 rounded-xl border border-border bg-card p-4"><h4 className="font-semibold">{title}</h4>{children}</div>}
